/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.RESMS.mainMenu;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author JohnLloydProg
 */
public class MenuFrame extends javax.swing.JFrame {
    
    private MainMenu menu;
    private PropertyDisplay_Available available;
    private PropertyDisplay_Reserved reserved;
    private PropertyDisplay_Sold sold;
    private CreateReservation reservation;
    public CardLayout cardLayout;
    public JPanel container;
    
    /**
     * Creates new form MainMenu
     */
    public MenuFrame() {
        initComponents();
        this.cardLayout = new CardLayout();
        this.container = new JPanel();
        this.container.setLayout(this.cardLayout);
        this.container.setName("Container");
        
        this.menu = new MainMenu(this);
        this.menu.setName("Main Menu");
        this.available = new PropertyDisplay_Available(this);
        this.available.setName("Display Available");
        this.reserved = new PropertyDisplay_Reserved(this);
        this.reserved.setName("Display Reserved");
        this.sold = new PropertyDisplay_Sold(this);
        this.sold.setName("Display Sold");
        this.reservation = new CreateReservation(this);
        this.reservation.setName("Create Reservation");
        
        this.container.add("Main Menu", this.menu);
        this.container.add("Display Available",this.available);
        this.container.add("Display Reserved", this.reserved);
        this.container.add("Display Sold", this.sold);
        this.container.add("Create Reservation", this.reservation);
        
        this.menu.initPropertiesButton();
        this.cardLayout.show(this.container, "Main Menu");
        this.add(this.container);
    }
    
    public Component getPanel(String name) {
        Component panel = null;
        for (Component component : this.container.getComponents()) {
            if (component.getName().contentEquals(name)) {
                panel = component;
            }
        }
        return panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    // End of variables declaration//GEN-END:variables
}
