/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OfferManagement;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JPanel;

/**
 *
 * @author Audrize Cruz
 */
public class DisplayOffers extends javax.swing.JFrame {

public class GradientPanel extends JPanel {

    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D)g.create();
        int w = getWidth();
        int h = getHeight();

        GradientPaint gp = new GradientPaint(
                0, 0, new Color(2, 48, 71),
                0, h, new Color(142, 202, 230));

        g2d.setPaint(gp);
        g2d.fillRect(0, 0, w, h);

        g2d.dispose();
    }
}
    public DisplayOffers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DashboardBackground = new javax.swing.JPanel();
        ListOfOffers = new javax.swing.JLabel();
        Arrow = new javax.swing.JLabel();
        RejectButton = new javax.swing.JButton();
        AcceptButton = new javax.swing.JButton();
        Menu = new GradientPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 200), new java.awt.Dimension(379, 40), new java.awt.Dimension(200, 200));
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 200), new java.awt.Dimension(379, 10), new java.awt.Dimension(200, 200));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 200), new java.awt.Dimension(379, 2), new java.awt.Dimension(200, 200));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 200), new java.awt.Dimension(379, 10), new java.awt.Dimension(200, 200));
        MenuButton = new javax.swing.JButton();
        ManageBuyerButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        OfferInfo = new javax.swing.JPanel();
        OfferInfoText = new javax.swing.JLabel();
        OfferList = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setResizable(false);
        setSize(new java.awt.Dimension(1600, 900));

        DashboardBackground.setBackground(new java.awt.Color(255, 255, 255));

        ListOfOffers.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        ListOfOffers.setForeground(new java.awt.Color(2, 48, 71));
        ListOfOffers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/angle-small-right.png"))); // NOI18N
        ListOfOffers.setIconTextGap(7);

        Arrow.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        Arrow.setForeground(new java.awt.Color(2, 48, 71));
        Arrow.setText("List of Offers");
        Arrow.setIconTextGap(7);

        RejectButton.setBackground(new java.awt.Color(36, 79, 99));
        RejectButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RejectButton.setForeground(new java.awt.Color(255, 255, 255));
        RejectButton.setText("REJECT");
        RejectButton.setBorder(null);
        RejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RejectButtonActionPerformed(evt);
            }
        });

        AcceptButton.setBackground(new java.awt.Color(36, 79, 99));
        AcceptButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AcceptButton.setForeground(new java.awt.Color(255, 255, 255));
        AcceptButton.setText("ACCEPT");
        AcceptButton.setBorder(null);
        AcceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptButtonActionPerformed(evt);
            }
        });

        Menu.setBackground(new java.awt.Color(2, 48, 71));
        Menu.setMaximumSize(new java.awt.Dimension(379, 1024));
        Menu.setMinimumSize(new java.awt.Dimension(379, 1024));
        Menu.setPreferredSize(new java.awt.Dimension(379, 1024));
        Menu.add(filler4);

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 1, 55)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/house-chimney.png"))); // NOI18N
        jLabel3.setText("ASCEND");
        jLabel3.setIconTextGap(15);
        Menu.add(jLabel3);

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("PROPERTIES");
        jLabel5.setIconTextGap(15);
        Menu.add(jLabel5);
        Menu.add(filler7);

        filler5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Menu.add(filler5);
        Menu.add(filler6);

        MenuButton.setBackground(new java.awt.Color(61, 131, 164));
        MenuButton.setFont(MenuButton.getFont().deriveFont(MenuButton.getFont().getStyle() | java.awt.Font.BOLD, MenuButton.getFont().getSize()+12));
        MenuButton.setForeground(new java.awt.Color(255, 255, 255));
        MenuButton.setText("     Main Menu");
        MenuButton.setToolTipText("");
        MenuButton.setBorder(null);
        MenuButton.setBorderPainted(false);
        MenuButton.setContentAreaFilled(false);
        MenuButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MenuButton.setMinimumSize(new java.awt.Dimension(379, 59));
        MenuButton.setPreferredSize(new java.awt.Dimension(379, 59));
        MenuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuButtonMouseExited(evt);
            }
        });
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });
        Menu.add(MenuButton);

        ManageBuyerButton.setBackground(new java.awt.Color(61, 131, 134));
        ManageBuyerButton.setFont(ManageBuyerButton.getFont().deriveFont(ManageBuyerButton.getFont().getStyle() | java.awt.Font.BOLD, ManageBuyerButton.getFont().getSize()+12));
        ManageBuyerButton.setForeground(new java.awt.Color(255, 255, 255));
        ManageBuyerButton.setText("     Manage Buyers");
        ManageBuyerButton.setBorder(null);
        ManageBuyerButton.setBorderPainted(false);
        ManageBuyerButton.setContentAreaFilled(false);
        ManageBuyerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ManageBuyerButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ManageBuyerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ManageBuyerButton.setMinimumSize(new java.awt.Dimension(379, 59));
        ManageBuyerButton.setPreferredSize(new java.awt.Dimension(379, 59));
        ManageBuyerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ManageBuyerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ManageBuyerButtonMouseExited(evt);
            }
        });
        ManageBuyerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageBuyerButtonActionPerformed(evt);
            }
        });
        Menu.add(ManageBuyerButton);
        Menu.add(filler1);

        OfferInfo.setBackground(new java.awt.Color(241, 241, 241));
        OfferInfo.setMaximumSize(new java.awt.Dimension(700, 700));
        OfferInfo.setMinimumSize(new java.awt.Dimension(700, 700));
        OfferInfo.setName(""); // NOI18N
        OfferInfo.setPreferredSize(new java.awt.Dimension(700, 700));

        OfferInfoText.setBackground(new java.awt.Color(255, 255, 255));
        OfferInfoText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        OfferInfoText.setForeground(new java.awt.Color(2, 48, 71));
        OfferInfoText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        OfferInfoText.setText("Offer Information");
        OfferInfoText.setFocusable(false);
        OfferInfoText.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Buyer", "Property", "Payment Method"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setColumnSelectionAllowed(true);
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jTable2.getTableHeader().setReorderingAllowed(false);
        OfferList.setViewportView(jTable2);
        jTable2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout OfferInfoLayout = new javax.swing.GroupLayout(OfferInfo);
        OfferInfo.setLayout(OfferInfoLayout);
        OfferInfoLayout.setHorizontalGroup(
            OfferInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OfferList)
            .addGroup(OfferInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OfferInfoText, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        OfferInfoLayout.setVerticalGroup(
            OfferInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OfferInfoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(OfferInfoText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OfferList, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DashboardBackgroundLayout = new javax.swing.GroupLayout(DashboardBackground);
        DashboardBackground.setLayout(DashboardBackgroundLayout);
        DashboardBackgroundLayout.setHorizontalGroup(
            DashboardBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardBackgroundLayout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(DashboardBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DashboardBackgroundLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(DashboardBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OfferInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(DashboardBackgroundLayout.createSequentialGroup()
                                .addComponent(Arrow)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ListOfOffers, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(DashboardBackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AcceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 55, Short.MAX_VALUE))
        );
        DashboardBackgroundLayout.setVerticalGroup(
            DashboardBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 2541, Short.MAX_VALUE)
            .addGroup(DashboardBackgroundLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(DashboardBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Arrow)
                    .addComponent(ListOfOffers, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(DashboardBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DashboardBackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OfferInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DashboardBackgroundLayout.createSequentialGroup()
                        .addGap(632, 632, 632)
                        .addGroup(DashboardBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AcceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DashboardBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DashboardBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1616, 908));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuButtonActionPerformed

    private void MenuButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuButtonMouseExited
       this.MenuButton.setContentAreaFilled(false);
    }//GEN-LAST:event_MenuButtonMouseExited

    private void MenuButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuButtonMouseEntered
       this.MenuButton.setBackground(new Color(36, 79, 99 ));
       this.MenuButton.setContentAreaFilled(true);
    }//GEN-LAST:event_MenuButtonMouseEntered

    private void ManageBuyerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageBuyerButtonActionPerformed
        DisplayBuyers newForm = new DisplayBuyers(); 
        newForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_ManageBuyerButtonActionPerformed

    private void ManageBuyerButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageBuyerButtonMouseExited
        this.ManageBuyerButton.setContentAreaFilled(false);
    }//GEN-LAST:event_ManageBuyerButtonMouseExited

    private void ManageBuyerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageBuyerButtonMouseEntered
       this.ManageBuyerButton.setBackground(new Color(36, 79, 99 ));
       this.ManageBuyerButton.setContentAreaFilled(true);
    }//GEN-LAST:event_ManageBuyerButtonMouseEntered

    private void RejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RejectButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RejectButtonActionPerformed

    private void AcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcceptButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayOffers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayOffers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayOffers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayOffers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayOffers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptButton;
    private javax.swing.JLabel Arrow;
    private javax.swing.JPanel DashboardBackground;
    private javax.swing.JLabel ListOfOffers;
    private javax.swing.JButton ManageBuyerButton;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton MenuButton;
    private javax.swing.JPanel OfferInfo;
    private javax.swing.JLabel OfferInfoText;
    private javax.swing.JScrollPane OfferList;
    private javax.swing.JButton RejectButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
