/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.RESMS.myapps;

import com.RESMS.libs.fileSystem.Add;
import com.RESMS.libs.fileSystem.Update;
import com.RESMS.libs.fileSystem.Delete;
import com.RESMS.libs.fileSystem.Read;
import com.RESMS.libs.object.Buyer;
import com.RESMS.libs.object.Employee;
import com.RESMS.libs.object.Offer;
import com.RESMS.libs.object.Transaction;
import com.RESMS.libs.object.Property;
import com.RESMS.mainMenu.MenuFrame;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Audrize Cruz
 */
public class DisplayOffers extends javax.swing.JFrame {

public class GradientPanel extends JPanel {

    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D)g.create();
        int w = getWidth();
        int h = getHeight();

        GradientPaint gp = new GradientPaint(
                0, 0, new Color(2, 48, 71),
                0, h, new Color(142, 202, 230));

        g2d.setPaint(gp);
        g2d.fillRect(0, 0, w, h);

        g2d.dispose();
    }
}
    public DisplayOffers() {
        initComponents();
        populateTable();
        setBuyers();
    }
    
    public void setBuyers(){
        ArrayList<Buyer> Buyers = Read.getBuyers();
        for(Buyer buyer : Buyers){
            SelectBuyers.addItem(buyer.getId());
        }
    }
    
    public void populateTable(){
        ArrayList<Offer> Offers = Read.getOffers();
        if(Offers.isEmpty()){
            
        }
        else{
        String columns[] = {"Offer ID","Property","Final Price","Currency"};
        String data[][] = new String[Offers.size()][4];
        for(int i =0; i < Offers.size(); i++){
            data[i][0] = Offers.get(i).getId();
            data[i][1] = "Block " + Offers.get(i).getCurrentProperty().getBlock() + " Lot " + Offers.get(i).getCurrentProperty().getLot();
            data[i][2] = String.valueOf(Offers.get(i).getPaymentMethod().getFinalPrice());
            data[i][3] = Offers.get(i).getCurrency();
        }
        DefaultTableModel model = new DefaultTableModel(data,columns) {

    @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
};
        OffersTable.setModel(model);
        }
        OffersTable.getTableHeader().setResizingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DashboardBackground = new javax.swing.JPanel();
        ListOfOffers = new javax.swing.JLabel();
        Arrow = new javax.swing.JLabel();
        RejectButton = new javax.swing.JButton();
        AcceptButton = new javax.swing.JButton();
        Menu = new GradientPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 200), new java.awt.Dimension(379, 40), new java.awt.Dimension(200, 200));
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 200), new java.awt.Dimension(379, 10), new java.awt.Dimension(200, 200));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 200), new java.awt.Dimension(379, 2), new java.awt.Dimension(200, 200));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 200), new java.awt.Dimension(379, 10), new java.awt.Dimension(200, 200));
        MenuButton = new javax.swing.JButton();
        ManageBuyerButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        OfferInfo = new javax.swing.JPanel();
        OfferInfoText = new javax.swing.JLabel();
        OfferList = new javax.swing.JScrollPane();
        OffersTable = new javax.swing.JTable();
        SelectBuyers = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        CreateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RESMS | ASCEND - Display Offers");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setResizable(false);
        setSize(new java.awt.Dimension(1600, 900));

        DashboardBackground.setBackground(new java.awt.Color(255, 255, 255));

        ListOfOffers.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        ListOfOffers.setForeground(new java.awt.Color(2, 48, 71));
        ListOfOffers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/angle-small-right.png"))); // NOI18N
        ListOfOffers.setIconTextGap(7);

        Arrow.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        Arrow.setForeground(new java.awt.Color(2, 48, 71));
        Arrow.setText("List of Offers");
        Arrow.setIconTextGap(7);

        RejectButton.setBackground(new java.awt.Color(36, 79, 99));
        RejectButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RejectButton.setForeground(new java.awt.Color(255, 255, 255));
        RejectButton.setText("REJECT");
        RejectButton.setBorder(null);
        RejectButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RejectButtonMouseClicked(evt);
            }
        });

        AcceptButton.setBackground(new java.awt.Color(36, 79, 99));
        AcceptButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AcceptButton.setForeground(new java.awt.Color(255, 255, 255));
        AcceptButton.setText("ACCEPT");
        AcceptButton.setBorder(null);
        AcceptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcceptButtonMouseClicked(evt);
            }
        });

        Menu.setBackground(new java.awt.Color(2, 48, 71));
        Menu.setMaximumSize(new java.awt.Dimension(379, 1024));
        Menu.setMinimumSize(new java.awt.Dimension(379, 1024));
        Menu.setPreferredSize(new java.awt.Dimension(379, 1024));
        Menu.add(filler4);

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 1, 55)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/house-chimney.png"))); // NOI18N
        jLabel3.setText("ASCEND");
        jLabel3.setIconTextGap(15);
        Menu.add(jLabel3);

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("PROPERTIES");
        jLabel5.setIconTextGap(15);
        Menu.add(jLabel5);
        Menu.add(filler7);

        filler5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Menu.add(filler5);
        Menu.add(filler6);

        MenuButton.setBackground(new java.awt.Color(61, 131, 164));
        MenuButton.setFont(MenuButton.getFont().deriveFont(MenuButton.getFont().getStyle() | java.awt.Font.BOLD, MenuButton.getFont().getSize()+12));
        MenuButton.setForeground(new java.awt.Color(255, 255, 255));
        MenuButton.setText("     Main Menu");
        MenuButton.setToolTipText("");
        MenuButton.setBorder(null);
        MenuButton.setBorderPainted(false);
        MenuButton.setContentAreaFilled(false);
        MenuButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MenuButton.setMinimumSize(new java.awt.Dimension(379, 59));
        MenuButton.setPreferredSize(new java.awt.Dimension(379, 59));
        MenuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuButtonMouseExited(evt);
            }
        });
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });
        Menu.add(MenuButton);

        ManageBuyerButton.setBackground(new java.awt.Color(61, 131, 134));
        ManageBuyerButton.setFont(ManageBuyerButton.getFont().deriveFont(ManageBuyerButton.getFont().getStyle() | java.awt.Font.BOLD, ManageBuyerButton.getFont().getSize()+12));
        ManageBuyerButton.setForeground(new java.awt.Color(255, 255, 255));
        ManageBuyerButton.setText("     Manage Buyers");
        ManageBuyerButton.setBorder(null);
        ManageBuyerButton.setBorderPainted(false);
        ManageBuyerButton.setContentAreaFilled(false);
        ManageBuyerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ManageBuyerButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ManageBuyerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ManageBuyerButton.setMinimumSize(new java.awt.Dimension(379, 59));
        ManageBuyerButton.setPreferredSize(new java.awt.Dimension(379, 59));
        ManageBuyerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ManageBuyerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ManageBuyerButtonMouseExited(evt);
            }
        });
        ManageBuyerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageBuyerButtonActionPerformed(evt);
            }
        });
        Menu.add(ManageBuyerButton);
        Menu.add(filler1);

        OfferInfo.setBackground(new java.awt.Color(241, 241, 241));
        OfferInfo.setMaximumSize(new java.awt.Dimension(700, 700));
        OfferInfo.setMinimumSize(new java.awt.Dimension(700, 700));
        OfferInfo.setName(""); // NOI18N
        OfferInfo.setPreferredSize(new java.awt.Dimension(700, 700));

        OfferInfoText.setBackground(new java.awt.Color(255, 255, 255));
        OfferInfoText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        OfferInfoText.setForeground(new java.awt.Color(2, 48, 71));
        OfferInfoText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        OfferInfoText.setText("Offer Information");
        OfferInfoText.setFocusable(false);
        OfferInfoText.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        OffersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Offer ID", "Property", "Final Price", "Currency"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        OffersTable.setCellSelectionEnabled(false);
        OffersTable.setGridColor(new java.awt.Color(255, 255, 255));
        OffersTable.getTableHeader().setReorderingAllowed(false);
        OfferList.setViewportView(OffersTable);
        OffersTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (OffersTable.getColumnModel().getColumnCount() > 0) {
            OffersTable.getColumnModel().getColumn(0).setResizable(false);
            OffersTable.getColumnModel().getColumn(1).setResizable(false);
            OffersTable.getColumnModel().getColumn(2).setResizable(false);
            OffersTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout OfferInfoLayout = new javax.swing.GroupLayout(OfferInfo);
        OfferInfo.setLayout(OfferInfoLayout);
        OfferInfoLayout.setHorizontalGroup(
            OfferInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OfferList)
            .addGroup(OfferInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OfferInfoText, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        OfferInfoLayout.setVerticalGroup(
            OfferInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OfferInfoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(OfferInfoText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OfferList, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SelectBuyers.setPreferredSize(new java.awt.Dimension(455, 35));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Select Buyer:");
        jLabel1.setPreferredSize(new java.awt.Dimension(69, 25));

        label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label.setForeground(new java.awt.Color(204, 0, 0));
        label.setPreferredSize(new java.awt.Dimension(69, 25));

        CreateButton.setBackground(new java.awt.Color(36, 79, 99));
        CreateButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CreateButton.setForeground(new java.awt.Color(255, 255, 255));
        CreateButton.setText("CREATE");
        CreateButton.setBorder(null);
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DashboardBackgroundLayout = new javax.swing.GroupLayout(DashboardBackground);
        DashboardBackground.setLayout(DashboardBackgroundLayout);
        DashboardBackgroundLayout.setHorizontalGroup(
            DashboardBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardBackgroundLayout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(DashboardBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DashboardBackgroundLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(DashboardBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(OfferInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(DashboardBackgroundLayout.createSequentialGroup()
                                .addComponent(Arrow)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ListOfOffers, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardBackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SelectBuyers, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(CreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AcceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 55, Short.MAX_VALUE))
        );
        DashboardBackgroundLayout.setVerticalGroup(
            DashboardBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 2541, Short.MAX_VALUE)
            .addGroup(DashboardBackgroundLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(DashboardBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Arrow, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListOfOffers, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(DashboardBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DashboardBackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OfferInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DashboardBackgroundLayout.createSequentialGroup()
                        .addGap(632, 632, 632)
                        .addGroup(DashboardBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AcceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(DashboardBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SelectBuyers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(1705, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DashboardBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DashboardBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1616, 908));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
        // TODO add your handling code here:
        MenuFrame newForm = new MenuFrame(); 
        newForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_MenuButtonActionPerformed

    private void MenuButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuButtonMouseExited
       this.MenuButton.setContentAreaFilled(false);
    }//GEN-LAST:event_MenuButtonMouseExited

    private void MenuButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuButtonMouseEntered
       this.MenuButton.setBackground(new Color(36, 79, 99 ));
       this.MenuButton.setContentAreaFilled(true);
    }//GEN-LAST:event_MenuButtonMouseEntered

    private void ManageBuyerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageBuyerButtonActionPerformed
        DisplayBuyers newForm = new DisplayBuyers(); 
        newForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_ManageBuyerButtonActionPerformed

    private void ManageBuyerButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageBuyerButtonMouseExited
        this.ManageBuyerButton.setContentAreaFilled(false);
    }//GEN-LAST:event_ManageBuyerButtonMouseExited

    private void ManageBuyerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageBuyerButtonMouseEntered
       this.ManageBuyerButton.setBackground(new Color(36, 79, 99 ));
       this.ManageBuyerButton.setContentAreaFilled(true);
    }//GEN-LAST:event_ManageBuyerButtonMouseEntered

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        CreateOffer newForm = new CreateOffer(); 
        newForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_CreateButtonActionPerformed

    private void AcceptButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceptButtonMouseClicked
        Add add = new Add();
        String value = SelectBuyers.getSelectedItem().toString();
        String id = value.replaceAll("[^0-9]", ""); // regular expression
        
        int column = 0;
        int row = jTable2.getSelectedRow();
        String value2 = jTable2.getModel().getValueAt(row, column).toString();
        String id2 = value2.replaceAll("[^0-9]", ""); 
        
        //check if offer is already a part of the transaction.
        ArrayList<Transaction> Transactions = Read.getTransactions();
        boolean check = false;
        
        for(Transaction transaction : Transactions){
            if(transaction.getOffer().getId().equals(value2)){
                check = true;
            }
        }
        
        //if already a part of the transaction dont accept
        if(check){
            label.setText("Offer is already part of a transaction!");
        }else{
            Transaction newTransaction = new Transaction(Employee.getUser(),Read.getBuyer(Integer.parseInt(id)),Read.getOffer(Integer.parseInt(id2)));
            Property property = newTransaction.getOffer().getCurrentProperty();
            property.setOwner(newTransaction.getBuyer());
            add.item(newTransaction);
            property.fileAction(new Update());
            label.setText("Offer succesfully accepted!");
        }
    }//GEN-LAST:event_AcceptButtonMouseClicked

    private void RejectButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RejectButtonMouseClicked
        Delete delete = new Delete();
        int column = 0;
        int row = OffersTable.getSelectedRow();
        String value2 = OffersTable.getModel().getValueAt(row, column).toString();
        String id2 = value2.replaceAll("[^0-9]", ""); 
        

        //check if offer is already a part of the transaction.
        ArrayList<Transaction> Transactions = Read.getTransactions();
        boolean check = false;
        
        for(Transaction transaction : Transactions){
            if(transaction.getOffer().getId().equals(value2)){
                check = true;
            }
        }
        
        //if already a part of the transaction dont accept
        if(check){
            label.setText("Offer is already part of a transaction!");
        }else{
            Offer deleteOffer = Read.getOffer(Integer.parseInt(id2));
            delete.item(deleteOffer);
            label.setText("Offer succesfully deleted!");
            populateTable();
        }
<<<<<<< HEAD
    }//GEN-LAST:event_RejectButtonMouseClicked
=======
    }//GEN-LAST:event_RejectButtonActionPerformed

    private void AcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptButtonActionPerformed
        
        Add add = new Add();
        String value = SelectBuyers.getSelectedItem().toString();
        String id = value.replaceAll("[^0-9]", ""); // regular expression
        
        int column = 0;
        int row = OffersTable.getSelectedRow();
        String value2 = OffersTable.getModel().getValueAt(row, column).toString();
        String id2 = value2.replaceAll("[^0-9]", ""); 
        
        String value3 = SelectAgent.getSelectedItem().toString();
        String id3 = value3.replaceAll("[^0-9]", ""); // regular expression
        
        //check if offer is already a part of the transaction.
        ArrayList<Transaction> Transactions = Read.getTransactions();
        boolean check = false;
        
        for(Transaction transaction : Transactions){
            if(transaction.getOffer().getId().equals(value2)){
                check = true;
            }
        }
        
        //if already a part of the transaction dont accept
        if(check){
            label.setText("Offer is already part of a transaction!");
        }else{
            Transaction newTransaction = new Transaction(Read.getEmployee(Integer.parseInt(id3)),Read.getBuyer(Integer.parseInt(id)),Read.getOffer(Integer.parseInt(id2)));
            add.item(newTransaction);
            label.setText("Offer succesfully accepted!");
        }
    }//GEN-LAST:event_AcceptButtonActionPerformed

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        CreateOffer newForm = new CreateOffer(); 
        newForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_CreateButtonActionPerformed
>>>>>>> 61c37b74e937f716cd7aacbe630efc8aacb327c0

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayOffers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayOffers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayOffers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayOffers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayOffers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptButton;
    private javax.swing.JLabel Arrow;
    private javax.swing.JButton CreateButton;
    private javax.swing.JPanel DashboardBackground;
    private javax.swing.JLabel ListOfOffers;
    private javax.swing.JButton ManageBuyerButton;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton MenuButton;
    private javax.swing.JPanel OfferInfo;
    private javax.swing.JLabel OfferInfoText;
    private javax.swing.JScrollPane OfferList;
    private javax.swing.JTable OffersTable;
    private javax.swing.JButton RejectButton;
    private javax.swing.JComboBox<String> SelectBuyers;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
